-- ============================================================
-- 旧库增量：专区类目表（招品/BESTSELLER 两张独立类目表）
-- 只在缺少这两张表时创建，并从 categories 迁移数据（幂等，不引用缺失列）
-- Supabase SQL Editor 执行一次即可。
-- ============================================================

-- 超管判断函数（幂等，缺库可独立建）
create or replace function public.is_super_admin()
returns boolean
language sql security definer stable
as $$
  select exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.role = 'super_admin'
  );
$$;

-- 招品类目表
create table if not exists public.recruit_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order int not null default 1,
  created_at timestamptz not null default now()
);
alter table public.recruit_categories enable row level security;
drop policy if exists "authenticated read recruit_categories" on public.recruit_categories;
create policy "authenticated read recruit_categories" on public.recruit_categories for select to authenticated using (true);
drop policy if exists "admin insert recruit_categories" on public.recruit_categories;
create policy "admin insert recruit_categories" on public.recruit_categories for insert to authenticated with check (public.is_super_admin());
drop policy if exists "admin update recruit_categories" on public.recruit_categories;
create policy "admin update recruit_categories" on public.recruit_categories for update to authenticated using (true) with check (public.is_super_admin());
drop policy if exists "admin delete recruit_categories" on public.recruit_categories;
create policy "admin delete recruit_categories" on public.recruit_categories for delete to authenticated using (public.is_super_admin());

-- BESTSELLER类目表
create table if not exists public.bestseller_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order int not null default 1,
  created_at timestamptz not null default now()
);
alter table public.bestseller_categories enable row level security;
drop policy if exists "authenticated read bestseller_categories" on public.bestseller_categories;
create policy "authenticated read bestseller_categories" on public.bestseller_categories for select to authenticated using (true);
drop policy if exists "admin insert bestseller_categories" on public.bestseller_categories;
create policy "admin insert bestseller_categories" on public.bestseller_categories for insert to authenticated with check (public.is_super_admin());
drop policy if exists "admin update bestseller_categories" on public.bestseller_categories;
create policy "admin update bestseller_categories" on public.bestseller_categories for update to authenticated using (true) with check (public.is_super_admin());
drop policy if exists "admin delete bestseller_categories" on public.bestseller_categories;
create policy "admin delete bestseller_categories" on public.bestseller_categories for delete to authenticated using (public.is_super_admin());

-- 迁移数据：只取 name/sort_order，兼容旧库（categories 无 published 列）
insert into public.recruit_categories (name, sort_order)
select c.name, c.sort_order from public.categories c
on conflict (name) do nothing;

insert into public.bestseller_categories (name, sort_order)
select c.name, c.sort_order from public.categories c
on conflict (name) do nothing;

-- 校验
select 'recruit_categories' as t, count(*) from public.recruit_categories
union all select 'bestseller_categories', count(*) from public.bestseller_categories;
